---
apiVersion: v1
kind: Namespace
metadata:
  name: memory-leak
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memory-leak
  namespace: memory-leak
data:
  memory-leak.py: |-
    import time

    SLEEP_TIME = 15

    if __name__ == '__main__':
        big_list = []
        #for i in range(32):
        #    print(i, len(big_list))
        #    big_list.extend(list(range(2**i)))
        #    time.sleep(SLEEP_TIME)
        while True:
          big_list.extend(range(500000))
          time.sleep(1)
        print(big_list)
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memory-leak
  namespace: memory-leak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-leak
  template:
    metadata:
      name: memory-leak
      labels:
        app: memory-leak
    spec:
      containers:
      - name: python-processor
        image: python:3.6
        command: ["python", "/scripts/memory-leak.py"]
        resources:
          limits:
            memory: 5048Mi
            cpu: 500m
        volumeMounts:
        - name: memory-leak
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: memory-leak
        configMap:
          name: memory-leak
